name: deploy-on-push

on:
  push:
    branches: [main]

  workflow_dispatch:
    branches: [qa_branch]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Build Step
        shell: bash
        run: |
          npm ci
          npm run build

      - name: Upload to S3 as artifact
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
          source_dir: 'dist'
          destination_dir: '.'
